name: Sync

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *' # 每5分钟执行一次

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install requests

      - name: Run sync script
        run: python sync.py

      - name: Commit changes
        run: |
          git config --local user.email "123@qq.com"
          git config --local user.name "abc"
          git diff
          git status
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -am "Sync changes"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
          fi

      - name: Delete Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 30
          keep_minimum_runs: 10
